# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

mini_cheesecakes = Recipe.create( title: "Mini Cheesecakes", recipe_link: "https://www.cookingclassy.com/cheesecake-cupcakes/", image_link: "https://www.cookingclassy.com/wp-content/uploads/2013/04/mini-cheesecakes-01.jpg", recipe_origin: "Greece", recipe_type: "Dessert" )
mini_cheesecakes.ingredients << [ Ingredient.find_or_create_by( name: "Graham Crackers"), Ingredient.find_or_create_by(name: "Granulated Sugar"), Ingredient.find_or_create_by(name: "Butter"), Ingredient.find_or_create_by(name: "Cream Cheese"), Ingredient.find_or_create_by(name: "All Purpose Flour"), Ingredient.find_or_create_by(name: "Eggs"), Ingredient.find_or_create_by(name: "Vanilla Extract"), Ingredient.find_or_create_by(name: "Sour Cream"), Ingredient.find_or_create_by(name: "Heavy Cream") ]


chocolate_covered_strawberries = Recipe.create( title: "Chocolate Covered Strawberries", recipe_link: "https://www.cookingclassy.com/chocolate-covered-strawberries/", image_link: "https://www.cookingclassy.com/wp-content/uploads/2020/01/chocolate-covered-strawberries-15-768x1152.jpg", recipe_origin: "America", recipe_type: "Dessert" )
chocolate_covered_strawberries.ingredients << [ Ingredient.find_or_create_by( name: "Chocolate Chips"), Ingredient.find_or_create_by(name: "Fresh Strawberries"), Ingredient.find_or_create_by(name: "Coconut Oil") ]

banana_bread_muffins = Recipe.create!( title: "Banana Bread Muffins", recipe_link: "https://www.lovefromtheoven.com/banana-bread-muffins/", image_link: "https://www.lovefromtheoven.com/wp-content/uploads/2018/01/muffin-recipes-9845.webp", recipe_origin: "America", recipe_type: "Dessert")
banana_bread_muffins.ingredients << [ Ingredient.find_or_create_by( name: "All Purpose Flour"), Ingredient.find_or_create_by(name: "Baking Powder"), Ingredient.find_or_create_by(name: "Salt"), Ingredient.find_or_create_by(name: "Ripe Bananas"), Ingredient.find_or_create_by(name: "Butter"), Ingredient.find_or_create_by(name: "Brown Sugar"), Ingredient.find_or_create_by(name: "Eggs"), Ingredient.find_or_create_by(name: "Vanilla"), Ingredient.find_or_create_by(name: "Chocolate Chips") ]

spam_onigirazu = Recipe.create( title: "Spam Onigirazu", recipe_link: "https://www.justonecookbook.com/spam-onigirazu/", image_link: "https://v1.nitrocdn.com/KQYMGOLIdXGmoAcyJsPOrQDKktgCbwtG/assets/static/optimized/rev-e80bad3/wp-content/uploads/2016/06/Spam-Onigirazu-6907-II.jpg", recipe_origin: "Japan", recipe_type: "Appetizer")
spam_onigirazu.ingredients << [ Ingredient.find_or_create_by( name: "Eggs" ), Ingredient.find_or_create_by( name: "Spam" ), Ingredient.find_or_create_by( name: "Oil" ), Ingredient.find_or_create_by( name: "Nori (seaweed)" ), Ingredient.find_or_create_by( name: "Japanese Short Grain Rice" ), Ingredient.find_or_create_by( name: "Salt" ), Ingredient.find_or_create_by( name: "Furikake" ), Ingredient.find_or_create_by( name: "Lettuce" ), Ingredient.find_or_create_by( name: "Mirin" ), Ingredient.find_or_create_by( name: "Sake" ), Ingredient.find_or_create_by( name: "Soy Sauce" )]

misu_soup = Recipe.create( title: "Miso Soup", recipe_link: "https://www.justonecookbook.com/vegan-miso-soup/", image_link: "https://v1.nitrocdn.com/KQYMGOLIdXGmoAcyJsPOrQDKktgCbwtG/assets/static/optimized/rev-e80bad3/wp-content/uploads/2019/01/Vegan-Miso-Soup-I.jpg", recipe_origin: "Japan", recipe_type: "Appetizer")
misu_soup.ingredients << [ Ingredient.find_or_create_by( name: "Kombu" ), Ingredient.find_or_create_by( name: "Water" ), Ingredient.find_or_create_by( name: "Miso" ), Ingredient.find_or_create_by( name: "Wakame" ) ]

kongnamul_bap = Recipe.create( title: "Kongnamul Bap", recipe_link: "https://www.koreanbapsang.com/kongnamul-bap-soybean-sprouts-rice-bowl/", image_link: "https://www.koreanbapsang.com/wp-content/uploads/2011/12/DSC1057-2.jpg", recipe_origin: "Korea", recipe_type: "Lunch")
kongnamul_bap.ingredients << [ Ingredient.find_or_create_by( name: "Short Grain Rice" ), Ingredient.find_or_create_by( name: "Water" ), Ingredient.find_or_create_by( name: "Soy Bean Sprouts" ), Ingredient.find_or_create_by( name: "Garlic" ), Ingredient.find_or_create_by( name: "Soy Sauce" ), Ingredient.find_or_create_by( name: "Mirin" ), Ingredient.find_or_create_by( name: "Sesame Oil" ), Ingredient.find_or_create_by( name: "Kimchi Juice" ), Ingredient.find_or_create_by( name: "Red Chili Pepper Flakes" ), Ingredient.find_or_create_by( name: "Sugar" ), Ingredient.find_or_create_by( name: "Scallions" ) ]

kimchi_soondubu_jjigae = Recipe.create( title: "Kimchi Soondubu Jjigae", recipe_link: "https://www.koreanbapsang.com/kimchi-soondubu-jjigae-soft-tofu-stew-kimchi/", image_link: "https://www.koreanbapsang.com/wp-content/uploads/2015/01/DSC_06281-e1422146518897.jpg", recipe_origin: "Korea", recipe_type: "Appetizer")
kimchi_soondubu_jjigae.ingredients << [ Ingredient.find_or_create_by( name: "Soft Tofu" ), Ingredient.find_or_create_by( name: "Kimchi" ), Ingredient.find_or_create_by( name: "Beef" ), Ingredient.find_or_create_by( name: "Red Chili Pepper Flakes" ), Ingredient.find_or_create_by( name: "Garlic" ), Ingredient.find_or_create_by( name: "Sesame Oil" ), Ingredient.find_or_create_by( name: "Water" ), Ingredient.find_or_create_by( name: "Kimchi Juice" ), Ingredient.find_or_create_by( name: "Salted Shrimp" ), Ingredient.find_or_create_by( name: "Black Pepper" ), Ingredient.find_or_create_by( name: "Scallion" ), Ingredient.find_or_create_by( name: "Egg" ) ]

goi_cuon = Recipe.create( title: "Goi Cuon", recipe_link: "https://www.food.com/recipe/goi-cuon-vietnamese-cold-spring-rolls-20445", image_link: "https://img.sndimg.com/food/image/upload/c_thumb,q_80,w_588,h_331/v1/img/recipes/20/44/5/86AJD9ZkTESnkKw3zjIL_Goi%20Con%20Vietnamese%20Cold%20Spring%20Rolls%2020445%20-%20final%202.jpg", recipe_origin: "Vietnam", recipe_type: "Appetizer")
goi_cuon.ingredients << [ Ingredient.find_or_create_by( name: "Rice Paper Sheet" ), Ingredient.find_or_create_by( name: "Chicken" ), Ingredient.find_or_create_by( name: "Shrimp" ), Ingredient.find_or_create_by( name: "Cilantro" ), Ingredient.find_or_create_by( name: "Mint Leaves" ), Ingredient.find_or_create_by( name: "Lettuce" ), Ingredient.find_or_create_by( name: "Cucumber" ), Ingredient.find_or_create_by( name: "Brean Sprout" ), Ingredient.find_or_create_by( name: "Vermicelli Rice Noodles" ), Ingredient.find_or_create_by( name: "Hoisin Sauce" ), Ingredient.find_or_create_by( name: "Peanuts" ), Ingredient.find_or_create_by( name: "Nuoc Mam" ) ] 

ca_phe_da = Recipe.create( title: "Ca Phe Da", recipe_link: "http://kitchenconfidante.com/easy-vietnamese-iced-coffee-ca-phe-sua-da-recipe", image_link: "https://kitchenconfidante.com/wp-content/uploads/2012/06/Vietnamese-Iced-Coffee-Kitchen-Confidante.jpg", recipe_origin: "Vietnam", recipe_type: "Drink")
ca_phe_da.ingredients << [ Ingredient.find_or_create_by( name: "Dark French Roast Coffee" ), Ingredient.find_or_create_by( name: "Water" ), Ingredient.find_or_create_by( name: "Condensed Milk" ), Ingredient.find_or_create_by( name: "Ice" )  ]

